name: Hello World!

on: workflow_dispatch

jobs: 
  hello_world:
    runs-on: windows-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World!"

  now_it_is:
    runs-on: windows-latest
    steps:
      - name: Now it is
        run: |
          date

  directory_content:
    runs-on: windows-latest
    steps:
      - name: Directory content
        run: |
          ls -l
          
